name: Auto Tag Version

# NOTE: This workflow requires a Personal Access Token (PAT) with 'repo' scope
# to be added as a repository secret named 'PAT' to trigger other workflows.
# Without a PAT, the tag push won't trigger the build-and-publish workflow.

on:
  push:
    branches:
      - main
    paths:
      - 'pom.xml'

permissions:
  contents: write  # This gives the workflow permission to create and push tags

jobs:
  tag-version:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip-tag')"
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # Use a PAT instead of GITHUB_TOKEN to trigger other workflows
          token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
          
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Extract version from pom.xml
        id: get-version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Extracted version: $VERSION"
          
      - name: Check if tag exists
        id: check-tag
        run: |
          TAG="v${{ steps.get-version.outputs.version }}"
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists"
            echo "tag_exists=true" >> $GITHUB_OUTPUT
          else
            echo "Tag $TAG does not exist"
            echo "tag_exists=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Create and push tag
        if: steps.check-tag.outputs.tag_exists == 'false'
        run: |
          TAG="v${{ steps.get-version.outputs.version }}"
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag -a "$TAG" -m "Release $TAG"
          
          # Use PAT if available to ensure the tag push triggers other workflows
          if [[ -n "${{ secrets.PAT }}" ]]; then
            git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }}
          fi
          
          git push origin "$TAG"
          echo "Created and pushed tag: $TAG"